### ISSUE TITLE
Add MSCollection to MSGraphClientModels header file

### ISSUE THREAD

**Issue by tobihagemann** [microsoftgraph/msgraph-sdk-objc-models#33]
I noticed that `MSCollection` is not part of [`MSGraphClientModels.h`](https://github.com/microsoftgraph/msgraph-sdk-objc-models/blob/04d36d437b36a51dffe286affde8f388a9b87361/GeneratedModels/MSGraphClientModels.h). It's not a huge deal because I can add `#import <MSGraphClientModels/MSCollection.h>` in my project since this public header file is exposed. But I believe it would help a lot if it's being added to the main public header file.

Furthermore, [this documented example](https://docs.microsoft.com/en-us/graph/api/driveitem-list-children?view=graph-rest-1.0&tabs=objc) on listing the contents of a folder doesn't use `MSCollection` and deserializes the object "manually" with `NSJSONSerialization`. It could be easily improved by replacing that with:

```objc
MSCollection *collection = [[MSCollection alloc] initWithData:data error:&error];
```

I was even actively looking for `MSCollection` but couldn't find it at first because it's not part of the main public header file.

**Comment by darrelmiller** [comment]
@andrueastman  Is there a reason why we didn't use the MSCollection as part of the snippet for deserializing the collection?

**Comment by andrueastman** [comment]
@darrelmiller There was no reason for this. I agree that using  MSCollection would be a valuable improvement to the snippets.
