### ISSUE TITLE
JSON serialization of MSGraphFolder crashes

### ISSUE THREAD

**Issue by dylanashe** [microsoftgraph/msgraph-sdk-objc-models#63]
**Primary Issue**
**msgraph-sdk-objc-models version 1.3.0**
**Xcode 11.5**

JSON serialization of MSGraphFolder crashes:

2020-06-30 09:22:14.178292-0700 xxxxxxx[38278:2457730] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (MSGraphFolder)'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e3cf0e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50ba89b2 objc_exception_throw + 48
	2   Foundation                          0x00007fff259fa44c _writeJSONValue + 227
	3   Foundation                          0x00007fff259fda33 ___writeJSONObject_block_invoke + 371
	4   CoreFoundation                      0x00007fff23ec5c57 __NSDICTIONARY_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	5   CoreFoundation                      0x00007fff23e9f77a -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 250
	6   Foundation                          0x00007fff259fd003 _writeJSONObject + 475
	7   Foundation                          0x00007fff259fa320 -[_NSJSONWriter dataWithRootObject:options:error:] + 86
	8   Foundation                          0x00007fff259fc3fa +[NSJSONSerialization dataWithJSONObject:options:error:] + 145
....

To reproduce the issue

1) Go to your example https://docs.microsoft.com/en-us/graph/api/driveitem-post-children?view=graph-rest-1.0&tabs=objc
2) Copy the ObjC example
3) Build and run

Application crashes when serializing JSON.

**Secondary issue:**

The conflict behavior code in your example does not compile:

[driveItem set@microsoft.graph.conflictBehavior:@"rename"];

---

The code:

```
MSHTTPClient *httpClient = [MSClientFactory createHTTPClientWithAuthenticationProvider:authenticationProvider];

NSString *MSGraphBaseURL = @"https://graph.microsoft.com/v1.0/";
NSMutableURLRequest *urlRequest = [NSMutableURLRequest requestWithURL:[NSURL URLWithString:[MSGraphBaseURL stringByAppendingString:@"/me/drive/root/children"]]];
[urlRequest setHTTPMethod:@"POST"];
[urlRequest setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];

MSGraphDriveItem *driveItem = [[MSGraphDriveItem alloc] init];
[driveItem setName:@"New Folder"];
MSGraphFolder *folder = [[MSGraphFolder alloc] init];
[driveItem setFolder:folder];
[driveItem set@microsoft.graph.conflictBehavior:@"rename"];

NSError *error;
NSData *driveItemData = [driveItem getSerializedDataWithError:&error];
[urlRequest setHTTPBody:driveItemData];

MSURLSessionDataTask *meDataTask = [httpClient dataTaskWithRequest:urlRequest 
	completionHandler: ^(NSData *data, NSURLResponse *response, NSError *nserror) {

		//Request Completed

}];

[meDataTask execute];
```

**Comment by dylanashe** [comment]
Also seeing a similar issue with MSGraphItemReference:

2020-07-01 19:26:48.684773-0700 xxxxxxx[50324:3672790] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid type in JSON write (MSGraphItemReference)'

**Comment by MIchaelMainer** [comment]
@dylanashe Thank you for bringing this to our attention. This is a bug in the client. Here's a workaround:

```obj-c
// Replace the existing alloc-init with
NSDictionary *conflictBehavior = [NSDictionary dictionaryWithObject:@"rename" forKey:@"microsoft.graph.conflictBehavior"];
MSGraphDriveItem *driveItem = [[MSGraphDriveItem alloc] initWithDictionary:conflictBehavior];
// Delete the attempt to set the non-existent property named microsoft.graph.conflictBehavior.
```


@ddyett @zengin 

We managed to not add an additionalData dictionary to [MSObject](https://github.com/microsoftgraph/msgraph-sdk-objc-models/blob/af0518ec31da0727b739db9d1b578ffc7f7197d7/BaseModels/MSObject.h), only [MSCollection](https://github.com/microsoftgraph/msgraph-sdk-objc-models/blob/af0518ec31da0727b739db9d1b578ffc7f7197d7/BaseModels/MSCollection.h#L24). We need to add that to support instance annotations and open types.
