### ISSUE TITLE
@microsoft.graph.downloadUrl

### ISSUE THREAD

**Issue by RegisStGelais** [microsoftgraph/msgraph-sdk-objc-models#65]
I parse the /children result into a MSGraphEntity and then iterate each MsGraphDriveItem in it.

Why is it that the DriveItems do not contain the "@microsoft.graph.downloadUrl" property ??

Is there another way to get it ?

(Note: I work in Swift)

Regards,

**Comment by MIchaelMainer** [comment]
@RegisStGelais That property represents an instance annotation (not part of the schema) and it not always present when working with DriveItem. You can access it via getDictionary from [MSObject](https://github.com/microsoftgraph/msgraph-sdk-objc-models/blob/master/BaseModels/MSObject.h#L26).

**Comment by RegisStGelais** [comment]
Exactly what I needed. Tks
